server:
  port: 80

spring:
 datasource:
  driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  url: jdbc:log4jdbc:mariadb://database-1.cfgx2qujhrsw.ap-northeast-2.rds.amazonaws.com:3306/EZEN
  username: admin
  password: nwhsck2891!
  hikari:
   minimum-idle: 2
   maximum-pool-size: 5
   auto-commit: false
 mvc:
  view:
   prefix: /WEB-INF/
   suffix: .jsp
 servlet:
    multipart:
      location: /java-work/upload
      max-file-size: 50MB
      max-request-size: 100MB
      
  
mybatis:
  type-aliases-package: com.hellow.vo
  mapper-locations: mapper/**/*.xml
  configuration:
   map-underscore-to-camel-case: true