SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS TEST_BOARD;




/* Create Tables */

CREATE TABLE TEST_BOARD
(
	TB_NUM int NOT NULL AUTO_INCREMENT,
	TB_WRITER varchar(400) NOT NULL,
	TB_REGION varchar(30) NOT NULL,
	TB_CATEGORY varchar(30) NOT NULL,
	TB_TITLE varchar(400) NOT NULL,
	TB_CONTENT text NOT NULL,
	TB_CREDAT char(8) NOT NULL,
	TB_MODDAT char(8) NOT NULL,
	TB_CNT int DEFAULT 0 NOT NULL,
	PRIMARY KEY (TB_NUM)
);



